services:
  - type: web
    name: evolucion-nominas-backend
    env: node
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: FIREBASE_API_KEY
        value: YOUR_FIREBASE_API_KEY
      - key: FIREBASE_AUTH_DOMAIN
        value: YOUR_FIREBASE_AUTH_DOMAIN
      - key: FIREBASE_PROJECT_ID
        value: YOUR_FIREBASE_PROJECT_ID
      - key: FIREBASE_STORAGE_BUCKET
        value: YOUR_FIREBASE_STORAGE_BUCKET
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: YOUR_FIREBASE_MESSAGING_SENDER_ID
      - key: FIREBASE_APP_ID
        value: YOUR_FIREBASE_APP_ID
      - key: JWT_SECRET
        value: YOUR_JWT_SECRET
